import { Metadata } from 'next';
import { Header } from '@/shared/components/shared/header';
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      DASHBOARD
      <body>{children}</body>
    </html>
  );
}
